---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PGX.
--- DateTime: 6/1/2022 1:02 AM
---

-- x,y,z is the coords where the 3d text should display
-- font is font index I suggest 4
-- scale is scale of the text I suggest 0.35
-- exLines is amount of extra lines there should be, you can check your string before hand for /n default should be 0
-- rgb is a table ex. {r = 255, b = 255, g = 255}
-- exports['3dTextWithOutline']:DrawText3DWithOutline(x,y,z,text, font, scale, exLines, rgb)

local function GetCharCount(str)
	-- for this you can do str:len() if you want to include special characters other than then regex below
	local count = 0
	for k in str:gmatch("[%z\1-\127\194-\244][\128-\191]*") do
		count = count + 1
	end
	return count -- str:len()
end

local function AddTextToComponentSubstring(str)
	local chars = GetCharCount(str)
	if chars > 100 then
		local exLines = (chars%99 == 0) and chars/99 or (chars/99)+1
		for i = 0, exLines do
			AddTextComponentSubstringPlayerName(str:sub(i*99, (i*99)+99))
		end
	else
		AddTextComponentSubstringPlayerName(str)
	end
end



function DrawText3DWithOutline(x,y,z,text, font, scale, exLines, rgb)
	font = font
	scale = scale
	rgb = rgb
	local retval,screenX,screenY = GetScreenCoordFromWorldCoord(x,y,z)

	SetTextProportional(0)
	SetTextFont(font)
	SetTextScale(scale, scale)
	BeginTextCommandWidth("CELL_EMAIL_BCON")
	AddTextComponentSubstringPlayerName(text)

	local val = EndTextCommandGetWidth(false)

	SetTextFont(font)
	SetTextProportional(0)
	SetTextScale(scale,scale)
	SetTextColour(rgb.r,rgb.g,rgb.b,215)--r,g,b,a
	SetTextCentre(true)--true,false
	SetTextDropshadow(1,0,0,0,200)--distance,r,g,b,a
	SetTextEdge(1, 0, 0, 0, 255)

	BeginTextCommandDisplayText("CELL_EMAIL_BCON")
	AddTextToComponentSubstring(text)
	--AddTextComponentSubstringPlayerName(text)
	--print(MeasureStringWidth(text, font, scale))


	EndTextCommandDisplayText(screenX,screenY)

	local hightX = GetTextScaleHeight(scale, font)


	local factor = (string.len(text)) / 370
	local valX = (screenX - val/2) -0.0049
	local valY = (screenX + val/2) +0.0049
	if exLines == 0 then

		DrawRect(screenX,screenY+0.0125, 0.010+ val, 0.0390, 41, 11, 41, 98)

		DrawRect(screenX, screenY-0.0099, val+0.0079,0.005,188,188,188,166)
		DrawRect(screenX, screenY+0.0125+(0.0099*2),  val+0.0079,0.005,188,188,188,166)

		DrawRect(valX, screenY+0.0114,0.0025, (screenY+0.0125+(0.0099*2) - (screenY-0.0099)) + 0.005,188,188,188,166)
		DrawRect(valY, screenY+0.0114 ,0.0025, (screenY+0.0125+(0.0099*2) - (screenY-0.0099)) + 0.005,188,188,188,166)
	else
		DrawRect(screenX,screenY+0.0125 + ((0.0125*0.95)*exLines), 0.010+ val, 0.0390 + ((0.0390*0.62) * exLines), 41, 11, 41, 98)

		DrawRect(screenX, (screenY-0.0099), val+0.0079,0.005,188,188,188,166)
		DrawRect(screenX, (screenY+0.0125+(0.0099*2)) + ((0.0039+(0.0099*2)) * exLines), val+0.0079,0.005,188,188,188,166)

		DrawRect(valX, screenY+0.0118 + (0.0118*exLines),0.0025, ((screenY+0.0125+(0.0099*2) - (screenY-0.0099)) + 0.005) + ( (screenY+0.0125+(0.0099*2) - (screenY-0.0099) + 0.005) * exLines / 2),188,188,188,166)
		DrawRect(valY, screenY+0.0118 + (0.0118*exLines),0.0025, ((screenY+0.0125+(0.0099*2) - (screenY-0.0099)) + 0.005) + ( (screenY+0.0125+(0.0099*2) - (screenY-0.0099) + 0.005) * exLines / 2),188,188,188,166)
	end
end

exports("DrawText3DWithOutline", DrawText3DWithOutline)

