---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by PGX.
--- DateTime: 6/1/2022 1:11 AM
---

fx_version 'cerulean'
game 'gta5'
author 'PeterGreek#0001'
description '3dTextWithOutline'
version '1.0.0'
client_script 'fxclient.lua'
